openapi: 3.0.3
info:
  title: Bit Grid API
  description: Bit Grid API
  version: 0.1.0
  contact:
    name: API Support
    email: "umka.max@gmail.com"
servers:
  - url: http://localhost:8080
    description: Local API server
tags:
  - name: Grid
  - name: Column
  - name: Cell
paths:
  /grid:
    get:
      tags:
        - Grid
      summary: A list of grids
      operationId: getAll
      responses:
        200:
          description:
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/GridSummary'
    post:
      tags:
        - Grid
      summary:
      operationId: create
      responses:
        201:
          description: Grid created
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/GridDTO'
  /grid/column/{id}/common-prefix:
    get:
      tags:
        - Column
      summary: A longest common prefix of given column
      operationId: getCommonPrefix
      parameters:
        - in: path
          name: id
          description: Grid column identifier
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description:
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorInfo'
  /grid/column/{columnId}:
    post:
      tags:
        - Column
      summary:
      operationId: insert
      parameters:
        - in: path
          name: columnId
          description: Grid column identifier
          schema:
            type: integer
            format: int64
          required: true
      responses:
        201:
          description: Список корзин клиента (возможен пустой)
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorInfo'
  /grid/cell/{columnId}/{rowId}:
    post:
      tags:
        - Cell
      summary:
      operationId: set
      parameters:
        - in: path
          name: columnId
          description: Grid column identifier
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: rowId
          description: Grid column identifier
          schema:
            type: integer
            format: int64
          required: true
      responses:
        204:
          description:
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorInfo'
components:
  schemas:
    ErrorInfo:
      type: object
      description: Error info
      properties:
        code:
          type: number
          description: Код ошибки
        status:
          type: string
          description: Статус ошибки
        message:
          type: string
          description: Error message
        details:
          type: string
          description: Детальное описание ошибки
    GridSummary:
      type: object
      description: Grid data
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        cellSize:
          type: integer
          format: int32
    GridDTO:
      type: object
      description: Grid data
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        cellSize:
          type: integer
          format: int32
